//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkeyShop.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Characteristic_Id { get; set; }
    
        public virtual Characteristic Characteristic { get; set; }
        public virtual Product Product { get; set; }
    }
}
